#cloud-config
package_update: true
packages:
  - docker.io

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /var/lib/clickhouse
  - docker run -d --name clickhouse-server \
      --ulimit nofile=262144:262144 \
      -p 8123:8123 -p 9000:9000 \
      -v /var/lib/clickhouse:/var/lib/clickhouse \
      yandex/clickhouse-server
